JS bindings: convert resdet.mjs to TypeScript
The original JS module can be built with `make resdet.mjs` as long as
`npm install` has been run to add the TS compiler.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -307,3 +307,7 @@ else
 	echo "TEST_CFLAGS=$(pkg-config --cflags cmocka)" >> config.mak
 	echo "TEST_LIBS=$(pkg-config --libs cmocka)" >> config.mak
 fi
+
+if ! command -v emcc > /dev/null || ! command -v npm > /dev/null; then
+	echo "Note: Emspricpten and npm are required for building and testing the Emscripten bindings"
+fi
